Import('env')
sources = ['DODrawing.cpp',
           'BBDrawing.cpp',
           'BLDrawing.cpp',
           'OCamera.cpp',
           'GridLayerCamera.cpp',
           'DWDrawing.cpp',
           'ODrawing.cpp',
           'RHDrawing.cpp',
           'GridLayerDrawing.cpp',
           'MPDrawing.cpp',
           'expoparams.cpp',
           'Robox.cpp']
headers = ['DODrawing.hpp',
           'BBDrawing.hpp',
           'BLDrawing.hpp',
           'OCamera.hpp',
           'GridLayerCamera.hpp',
           'DWDrawing.hpp',
           'ODrawing.hpp',
           'RHDrawing.hpp',
           'GridLayerDrawing.hpp',
           'MPDrawing.hpp',
           'expoparams.hpp',
           'Robox.hpp']
env.StageLibrary(env.PrevLib('npmrobox', sources))
env.StageHeader('npm/robox', headers)
