# Platform.py and Environ.py originally from http://www.iplt.org/
from Platform import *
from Environ import *
platform = GetPlatform()

env = Environment(LIBPATH  = "#lib", CPPPATH  = "#inc")
platform.SetDebugCompilerFlags(env)

Export('env')
Export('platform')

SConscript(dirs = '.')
