SOURCES    =  \
MotionController.cpp \
MotionPlanner.cpp \
MotionPlannerFields.cpp \
MotionPlannerState.cpp 

LIBTARGET       = libsfloaexpo
EXTRAINCINSTALL = sfl/oa/expo
BASEDIR         = ../..

include ../../Makefile.cppinclude
