Import('env')
Import ('platform')

e = env.Copy(LIBS =
             ['npmrobox',
#              'npmestar',
#              'npmbiron',
              'npmlaas',
              'npmvisitor',
              'npmcommon',
              'sunflower',
#              'xcfglue',
#              'sigc-1.2',
#              'xcf',
#              'xmltio',
#              'estar',
              'm',
              'png',
              'z'])
#e.Append(LIBPATH = '/home/rolo/local-xcf/lib')
platform.SetGLStuff(e)

e.StageBinary(e.Program(target = 'nepumuk',
                        source = ['RobotFactory.cpp',
                                  'Interlock.cpp',
                                  'nepumuk.cpp',
                                  'Simulator.cpp']))

e.StageBinary(e.Program(target = 'dumpworld',
                        source = ['Interlock.cpp',
                                  'dumpworld.cpp']))

env.StageBinary(['testtheater.sh',
                 'robots.theater',
                 'layout.theater',
                 'tsr_2005-02-07.sh',
                 'robots.tsr_2005-02-07',
                 'expodemo.sh',
                 'robots.expo',
                 'layout.expo',
#                 'testestar.sh',
#                 'robots.estar',
#                 'layout.estar',
                 'ttademo.sh',
                 'robots.tta',
                 'layout.tta'])
