SOURCES = \
GridFrame.cpp \
GridLayer.cpp \
GridPlanner.cpp \
NF1.cpp \
NF1Wave.cpp \
Wave.cpp

LIBTARGET       = libsfloagplan
EXTRAINCINSTALL = sfl/oa/gplan
BASEDIR         = ../..

include ../../Makefile.cppinclude
