Import('env')
lib = env.StaticLibrary('sfloagplan',
                        ['NF1Wave.cpp',
                         'NF1.cpp',
                         'GridLayer.cpp',
                         'GridFrame.cpp'])
env.StageLibrary(lib)
env.StageHeader('sfl/gplan',
                ['NF1Wave.hpp',
                 'NF1.hpp',
                 'GridLayer.hpp',
                 'GridFrame.hpp'])
