SOURCES     = \
BubbleBand.cpp \
BubbleFactory.cpp \
ReplanHandler.cpp \
Bubble.cpp \
BubbleList.cpp

LIBTARGET       = libsfloabband
EXTRAINCINSTALL = sfl/oa/bband
BASEDIR         = ../..

include ../../Makefile.cppinclude
