SOURCES = \
DynamicWindow.cpp \
Lookup.cpp \
Objective.cpp \
DistanceObjective.cpp \
HeadingObjective.cpp \
SpeedObjective.cpp

LIBTARGET        = libsfloadwa
EXTRAINCINSTALL  = sfl/oa/dwa
BASEDIR          = ../..

include ../../Makefile.cppinclude
