Import('env')
lib = env.StaticLibrary('sfloadwa',
                        ['Lookup.cpp',
                         'SpeedObjective.cpp',
                         'HeadingObjective.cpp',
                         'DynamicWindow.cpp',
                         'DistanceObjective.cpp',
                         'Objective.cpp'])
env.StageLibrary(lib)
env.StageHeader('sfl/dwa',
                ['Lookup.hpp',
                 'SpeedObjective.hpp',
                 'HeadingObjective.hpp',
                 'DynamicWindow.hpp',
                 'DistanceObjective.hpp',
                 'Objective.hpp'])
